add cctv traj
MADRAS-crowds/madras-data-app pull request #3
Opened 2024-08-22 19:01 UTC by odufour7

- I modified the name of the cameras in the .json file to match the MADRAS article
- I added a new camera to the map the one at the exit of place des terreaux to match the MADRAS article
- I added a tab about visualisation in time and in space of trajectories on the place des terreaux. The data of cameras from airbnb just need to be updated to the right coordinate system (this can be added later in the python file also)
- I modified the contact_tab to make it more friendly and readable. 
- I still have to included analysis of CCTV cameras

2024-08-23 08:11 UTC, chraibi requested changes

2024-08-23 08:11 UTC, chraibi commented on src/tabs/animation_tab.py
> +from pyproj import Transformer
did you add pyproj to requirements.txt?

2024-08-23 08:11 UTC, chraibi commented on src/tabs/animation_tab.py
> +    print(pd_trajs.head())
remove print statement

2024-08-23 08:11 UTC, chraibi commented on src/tabs/contacts_tab.py
> +def plot_histogram(df: pd.DataFrame, bins: int, log_plot: Tuple[bool, bool]) -> plt.Figure:
docstring missing

2024-08-23 08:57 UTC, odufour7 commented on src/tabs/animation_tab.py
> +from pyproj import Transformer
not yet

2024-08-24 09:16 UTC, odufour7 commented
Ok, I have made the changes

2024-08-24 09:17 UTC, closed without merging