Contact and animations modifications
MADRAS-crowds/madras-data-app pull request #4
Opened 2024-08-24 09:24 UTC by odufour7

- I addressed your requests by adding docstrings, adjusting whitespaces, and updating the requirements.
- I modified the contact tab to directly interact with the CSV contact file sourced from the MADRAS My Core Cloud.
- I made some minor improvements to the animation style. Additionally, with the trajectories from the cloud, you can now view pedestrians from top-view cameras.

2024-09-13 06:39 UTC, chraibi requested changes
Thanks Oscar, this looks nice!
Could you please rename other_datasets to something meaninful like for example "gps_trajectories".

Could you also fix the CI?

2024-09-13 16:41 UTC, odufour7 commented
"Could you also fix the CI?" What does it mean "CI" ?

2024-09-15 16:38 UTC, odufour7 commented
I added a white background to enhance readability when the web browser has a black background. And, I incorporated survey data and renamed the folders within the data directory

2024-09-24 06:29 UTC, chraibi approved these changes

2024-09-24 06:29 UTC, merged